name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Jest Execution Permissions
      run: chmod +x node_modules/.bin/jest

    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm run test